#!/usr/bin/env bash
set -eu

usage() {
  cat <<EOL
Usage:
  $0 [Options]

Options:
  -a    display all menu
  -h    display this help and exit
  -l    use a long listing format
EOL
  exit
}

while getopts ahl OPT; do
  case $OPT in
  a)
    ALL=1
    ;;
  h)
    usage
    ;;
  l)
    LONG=1
    ;;
  \?)
    usage
    ;;
  esac
done

#Number,Name,Category,Type,Price,Calorie,Salt
MENU=$(
  cat <<EOL
SA01,小エビのサラダ(Lサイズ),sidedish,salad,500,189,2.1
SA02,小エビのサラダ,sidedish,salad,350,126,1.4
SA03,彩りイタリアンサラダ(Lサイズ),sidedish,salad,500,321,2.2
SA04,彩りイタリアンサラダ,sidedish,salad,350,214,1.5
SA05,チキンとブロッコリーのサラダ(Lサイズ),sidedish,salad,500,274,2.5
SA06,チキンとブロッコリーのサラダ,sidedish,salad,350,182,1.7
SA07,わかめとオクラのサラダ(Lサイズ),sidedish,salad,500,214,4.4
SA08,わかめとオクラのサラダ,sidedish,salad,350,143,3.0
SU01,コーンクリームスープ,sidedish,soup,150,142,1.1
SU02,レンズ豆とスペルト小麦のミネストローネ(季節限定),sidedish,soup,300,244,1.9
SU03,マッシュルームスープ(季節限定),sidedish,soup,150,130,0.9
SU04,たまねぎのズッパ,sidedish,soup,300,223,1.8
AP01,辛味チキン,sidedish,appetizer,300,374,2.2
AP02,アロスティチーニ,sidedish,appetizer,400,224,0.6
AP03,ほうれん草のソテー,sidedish,appetizer,200,123,1.1
AP04,ポップコーンシュリンプ,sidedish,appetizer,300,215,1.4
AP05,エスカルゴのオーブン焼き,sidedish,appetizer,400,256,1.6
AP06,柔らか青豆の温サラダ,sidedish,appetizer,200,214,0.9
AP07,チョリソー,sidedish,appetizer,400,393,2.0
AP08,フリウリ風フリコ,sidedish,appetizer,300,419,1.9
AP10,ムール貝のガーリック焼き,sidedish,appetizer,400,164,1.3
AP11,キャベツとアンチョビのソテー,sidedish,appetizer,200,85,1.7
AP12,フレッシュチーズとトマトのサラダ,sidedish,appetizer,300,195,0.4
AP13,セロリのピクルス(季節限定),sidedish,appetizer,200,52,1.3
AP14,熟成ミラノサラミ,sidedish,appetizer,300,95,1.1
AP16,プロシュート,sidedish,appetizer,400,162,1.8
AP17,アンチョビのフリコ,sidedish,appetizer,400,551,4.1
AP22,フレッシュチーズとトマトのサラダ(Wサイズ),sidedish,appetizer,600,390,0.8
AP21,アロスティチーニ(Wサイズ),sidedish,appetizer,800,448,1.2
AP23,プロシュート(Wサイズ),sidedish,appetizer,800,324,3.6
AP24,熟成ミラノサラミ(Wサイズ),sidedish,appetizer,600,190,2.2
AP25,スパイシーフリコ,sidedish,appetizer,350,425,3.3
DG01,ミラノ風ドリア,meal,doria,300,521,2.5
DG02,チーズたっぷりミラノ風ドリア,meal,doria,400,722,3.4
DG03,半熟卵のミラノ風ドリア,meal,doria,350,611,2.7
DG04,いろどり野菜のミラノ風ドリア,meal,doria,400,570,3.0
DG05,セットプチフォッカ付きミラノ風ドリア,meal,doria,400,628,2.9
DG06,ほうれん草のグラタン,meal,gratin,400,521,1.9
DG07,エビクリームグラタン,meal,gratin,400,517,2.1
DG08,シーフードパエリア,meal,rice,600,595,3.6
DG09,エビと野菜のトマトクリームリゾット,meal,rice,400,320,2.4
DG10,ハヤシ&ターメリックライス,meal,rice,500,676,3.9
DG11,半熟卵のハヤシ&ターメリックライス,meal,rice,550,766,4.1
PZ01,マルゲリータピザ,meal,pizza,400,568,2.5
PZ02,バッファローモッツァレラのピザ,meal,pizza,500,575,2.3
PZ03,パンチェッタのピザ,meal,pizza,400,646,2.9
PZ04,野菜ときのこのピザ,meal,pizza,400,593,2.9
PZ05,アンチョビとルーコラのピザ,meal,pizza,400,543,4.7
PZ06,たっぷりコーンのピザ,meal,pizza,400,669,2.8
PZ07,たらこクリームのピザ,meal,pizza,400,615,3.3
PA01,タラコソースシシリー風,meal,pasta,400,550,2.0
PA02,ミートソースボロニア風,meal,pasta,400,571,2.8
PA03,ペペロンチーノ,meal,pasta,300,497,1.6
PA04,パルマ風スパゲッティ,meal,pasta,400,716,2.7
PA05,カルボナーラ,meal,pasta,500,731,2.0
PA06,エビとブロッコリーのオーロラソース,meal,pasta,500,668,2.9
PA07,ペストジェノベーゼ,meal,pasta,500,679,1.7
PA08,アーリオ・オーリオ,meal,pasta,300,497,1.5
PA09,アラビアータ,meal,pasta,400,601,2.5
PA10,きのことパンチェッタのボスカイオーラ(季節限定),meal,pasta,500,729,3.3
PA11,イカの墨入りスパゲッティ,meal,pasta,500,578,2.4
PA12,半熟卵のミートソースボロニア風,meal,pasta,450,651,3.1
PA13,キャベツのペペロンチーノ,meal,pasta,400,663,1.9
PA14,ナポリジェノベーゼ(季節限定),meal,pasta,500,565,2.3
MT01,ハンバーグステーキ,meal,hamburg,400,560,2.8
MT02,若鶏のディアボラ風,meal,chicken,500,541,2.1
MT03,イタリアンハンバーグ,meal,hamburg,500,670,2.9
MT04,柔らかチキンのチーズ焼き,meal,chicken,500,588,2.0
MT06,チョリソーと若鶏の盛合せ,meal,chicken,600,694,2.8
MT07,ディアボラ風ハンバーグ,meal,hamburg,500,632,3.1
MT08,デミグラスソースのハンバーグ,meal,hamburg,500,606,3.1
MT09,リブステーキ,meal,steak,1000,606,2.0
MT10,グリルチキン&ハンバーグ,meal,hamburg,600,742,3.5
MT11,チキン&ハンバーグのディアボラ風,meal,hamburg,700,814,3.8
MT12,チーズのせチキン&ハンバーグ,meal,hamburg,700,947,4.1
PR01,ライス,sidedish,rice,150,303,0.0
PR02,ラージライス,sidedish,rice,200,454,0.0
PR03,スモールライス,sidedish,rice,100,151,0.0
RP04,シナモンプチフォッカ,sidedish,appetizer,200,246,0.8
RP05,セットプチフォッカ,sidedish,appetizer,100,107,0.4
RP06,プチフォッカ,sidedish,appetizer,150,214,0.8
RP08,ミニフィセル,sidedish,appetizer,150,188,1.0
PR09,ガーリックトースト,sidedish,appetizer,200,252,1.1
DE01,ティラミス クラシコ,sidedish,dessert,300,229,0.1
DE02,ヘーゼルナッツ(アイスケーキ・季節限定),sidedish,dessert,200,127,0.0
DE03,コーヒーゼリー(ミルクアイスのせ),sidedish,dessert,300,162,0.1
DE05,イタリアンジェラート,sidedish,dessert,250,121,0.1
DE06,イタリアンプリン,sidedish,dessert,250,216,0.1
DE07,チョコレートケーキ,sidedish,dessert,300,166,0.1
DE08,プリンとヘーゼルナッツの盛合せ(季節限定),sidedish,dessert,400,343,0.1
DE10,ブラッドオレンジのパンナコッタ(季節限定),sidedish,dessert,400,200,0.1
DE11,すっきりレモンのシャーベット,sidedish,dessert,200,127,0.0
DE12,プリンとティラミス クラシコの盛合せ,sidedish,dessert,500,445,0.2
DE13,トリフアイクリーム,sidedish,dessert,350,164,0.1
DE14,とろけるティラミス&コーヒーゼリー,sidedish,dessert,400,284,0.1
DE15,イタリアンジェラートのせコーヒーゼリー,sidedish,dessert,350,182,0.1
DE16,ティラミス クラシコ(ファミリーサイズ),sidedish,dessert,1800,1374,0.6
BR01,キリン一番搾り(ジョッキ),drink,alcohol,400,-,-
BR02,キリン一番搾り(グラスビール),drink,alcohol,300,-,-
BR03,サントリー オールフリー,drink,alcohol,250,-,-
BR04,サントリー -196℃ ストロングゼロ ダブルレモン,drink,alcohol,350,-,-
BR05,ラコンブリッコラ(45ml),drink,alcohol,300,-,-
WN01,フレッシュワイン(グラスワイン・赤),drink,alcohol,100,-,-
WN02,フレッシュワイン(グラスワイン・白),drink,alcohol,100,-,-
WN03,フレッシュワイン(デカンタ・赤・250ml),drink,alcohol,200,-,-
WN04,フレッシュワイン(デカンタ・白・250ml),drink,alcohol,200,-,-
WN05,フレッシュワイン(デカンタ・赤・500ml),drink,alcohol,400,-,-
WN06,フレッシュワイン(デカンタ・白・500ml),drink,alcohol,400,-,-
WN07,フレッシュワイン(マグナム・赤・1500ml),drink,alcohol,1100,-,-
WN08,フレッシュワイン(マグナム・白・1500ml),drink,alcohol,1100,-,-
WN12,ランブルスコ(ロゼ・甘口),drink,alcohol,1100,-,-
WN13,ドン ラファエロ(白・辛口),drink,alcohol,1100,-,-
WN14,ランブルスコ セッコ(赤・辛口),drink,alcohol,1100,-,-
WN15,ベルデッキオ(白・辛口・中),drink,alcohol,1100,-,-
WN16,キャンティ(赤・辛口・やや重い),drink,alcohol,1100,-,-
WN19,キャンティ ルフィナ リゼルパ(辛口・重い),drink,alcohol,2200,-,-
DB03,セットドリンクバー,drink,drinkbar,200,-,-
TP01,トッピング半熟卵,sidedish,topping,50,-,-
TP02,ペコリーノ・ロマーノ,sidedish,topping,100,47,0.5
TP03,ガルムソース&野菜ペースト,sidedish,topping,150,99,1.1
TP04,野菜ペースト,sidedish,topping,100,72,0.3
TP07,フルーツソース(カシス&ブルーベリー),sidedish,topping,100,40,0.0
FC01,皮つき新じゃがのチーズグラタン(季節限定),meal,barbecue,400,427,2.5
EOL
)

if [ -n "${ALL+x}" ]; then
  if [ -n "${LONG+x}" ]; then
    echo "${MENU}" | sed -E 's/^[^,]*,//'
  else
    echo "${MENU}" | awk -F, '{print $2}'
  fi
else
  if [ -n "${LONG+x}" ]; then
    echo "${MENU}" | shuf -n1 | sed -E 's/^[^,]*,//'
  else
    echo "${MENU}" | shuf -n1 | awk -F, '{print $2}'
  fi
fi
