#!/usr/bin/env bash
set -eu

usage() {
  cat << EOL
Usage:
  $0 [Options]

Options:
  -a    display all menu
  -h    display this help and exit
  -l    use a long listing format
EOL
  exit
}

while getopts ahl OPT; do
  case $OPT in
    a)
      ALL=1
      ;;
    h)
      usage
      ;;
    l)
      LONG=1
      ;;
    \?)
      usage
      ;;
  esac
done

#Number,Name,Category,Type,Price,Calorie,Salt
MENU=$(cat << EOL
A01,小エビのサラダ(Lサイズ),sidedish,salad,499,189,2.1
A02,小エビのサラダ,sidedish,salad,349,126,1.4
A03,彩りイタリアンサラダ(Lサイズ),sidedish,salad,499,375,2.5
A04,彩りイタリアンサラダ,sidedish,salad,349,250,1.7
A05,チキンとブロッコリーのサラダ(Lサイズ),sidedish,salad,499,274,2.5
A06,チキンとブロッコリーのサラダ,sidedish,salad,349,182,1.7
A07,わかめとオクラのサラダ(Lサイズ),sidedish,salad,499,214,4.4
A08,わかめとオクラのサラダ,sidedish,salad,349,143,3.0
A09,半熟卵のチキンとブロッコリーのサラダ,sidedish,salad,418,272,1.9
B01,コーンクリームスープ,sidedish,soup,149,142,1.1
B02,レンズ豆とスペルト小麦のミネストローネ(季節限定),sidedish,soup,299,244,1.9
B03,冷たいパンプキンスープ(季節限定),sidedish,soup,149,105,0.9
C01,辛味チキン,sidedish,appetizer,299,374,2.2
C03,ほうれん草のソテー,sidedish,appetizer,199,123,1.1
C04,ポップコーンシュリンプ,sidedish,appetizer,299,215,1.4
C05,エスカルゴのオーブン焼き,sidedish,appetizer,399,256,1.6
C06,柔らか青豆の温サラダ,sidedish,appetizer,199,214,0.9
C07,チョリソー,sidedish,appetizer,399,393,2.0
C08,フリウリ風フリコ,sidedish,appetizer,299,333,1.0
C10,ムール貝のガーリック焼き,sidedish,appetizer,399,164,1.3
C11,フレッシュチーズとトマトのサラダ,sidedish,appetizer,299,200,0.4
C12,セロリのピクルス(季節限定),sidedish,appetizer,199,52,1.3
C13,熟成ミラノサラミ,sidedish,appetizer,299,95,1.1
C15,プロシュート,sidedish,appetizer,399,162,1.8
C16,やみつきアンチョビのフリコ,sidedish,appetizer,399,465,3.2
C18,半熟卵のほうれん草のソテー,sidedish,appetizer,268,206,1.3
C19,ペコリーノチーズの柔らか青豆の温サラダ,sidedish,appetizer,299,308,1.8
C21,フレッシュチーズとトマトのサラダ(Wサイズ),sidedish,appetizer,598,400,0.8
C22,プロシュート(Wサイズ),sidedish,appetizer,798,324,3.6
C23,熟成ミラノサラミ(Wサイズ),sidedish,appetizer,598,190,2.2
D01,ミラノ風ドリア,meal,doria,299,521,2.5
D02,チーズたっぷりミラノ風ドリア,meal,doria,399,722,3.4
D03,半熟卵のミラノ風ドリア,meal,doria,368,611,2.7
D04,いろどり野菜のミラノ風ドリア,meal,doria,399,570,3.0
D05,セットプチフォッカ付きミラノ風ドリア,meal,doria,378,628,2.9
D06,エビとイカのドリア,meal,doria,499,624,2.9
D07,ほうれん草のグラタン,meal,gratin,399,521,1.9
D08,シーフードグラタン,meal,gratin,499,537,2.2
D09,シーフードパエリア,meal,rice,599,595,3.6
D10,エビと野菜のトマトクリームリゾット,meal,rice,399,311,2.3
D11,ハヤシ&ターメリックライス,meal,rice,499,676,3.9
D12,半熟卵のハヤシ&ターメリックライス,meal,rice,568,766,4.1
E01,マルゲリータピザ,meal,pizza,399,568,2.5
E02,バッファローモッツァレラのピザ,meal,pizza,499,575,2.3
E03,パンチェッタのピザ,meal,pizza,399,646,2.9
E04,野菜ときのこのピザ,meal,pizza,399,593,2.9
E05,アンチョビとルーコラのピザ,meal,pizza,399,543,4.7
E06,たっぷりコーンのピザ,meal,pizza,399,669,2.8
E07,たらこクリームのピザ,meal,pizza,399,615,3.3
E08,半熟卵のパンチェッタのピザ,meal,pizza,468,736,3.1
F01,タラコソースシシリー風,meal,pasta,399,550,2.0
F02,ミートソースボロニア風,meal,pasta,399,571,2.8
F03,ペペロンチーノ,meal,pasta,299,497,1.6
F04,パルマ風スパゲッティ,meal,pasta,399,672,2.6
F05,カルボナーラ,meal,pasta,499,738,2.1
F06,エビとブロッコリーのオーロラソース,meal,pasta,499,668,2.9
F07,ペストジェノベーゼ(季節限定),meal,pasta,499,772,2.2
F08,アーリオ・オーリオ,meal,pasta,299,497,1.5
F11,イカの墨入りスパゲッティ,meal,pasta,499,578,2.4
F13,半熟卵のミートソースボロニア風,meal,pasta,468,654,3.0
G01,ナポリジェノベーゼ,meal,pasta,499,528,2.3
G03,アラビアータ,meal,pasta,399,601,2.5
H01,ハンバーグステーキ,meal,hamburg,399,560,2.8
H02,若鶏のディアボラ風,meal,chicken,499,541,2.1
H03,イタリアンハンバーグ,meal,hamburg,499,670,2.9
H04,柔らかチキンのチーズ焼き,meal,chicken,499,588,2.0
H05,ミックスグリル,meal,hamburg,599,868,4.3
H06,チョリソーと若鶏の盛合せ,meal,chicken,599,694,2.8
H07,ディアボラ風ハンバーグ,meal,hamburg,499,632,3.1
H08,デミグラスソースのハンバーグ,meal,hamburg,499,606,3.1
H09,リブステーキ,meal,steak,999,606,2.0
H10,チキングリルとハンバーグの盛合せ,meal,hamburg,599,742,3.5
H11,ディアボラ風ソースのせチキングリルとハンバーグの盛合せ,meal,hamburg,699,814,3.8
H12,チーズのせチキングリルとハンバーグの盛合せ,meal,hamburg,699,947,4.1
J01,ライス,sidedish,rice,169,303,0.0
J02,ラージライス,sidedish,rice,219,454,0.0
J03,スモールライス,sidedish,rice,119,151,0.0
J04,シナモンフォッカチオ,sidedish,appetizer,169,246,0.8
J05,セットプチフォッカ,sidedish,appetizer,79,107,0.4
J06,プチフォッカ,sidedish,appetizer,139,214,0.8
J07,フォッカチオ,sidedish,appetizer,119,214,0.8
J08,ミニフィセル,sidedish,appetizer,169,188,1.0
J09,ガーリックトースト,sidedish,appetizer,189,252,1.1
K01,ティラミス クラシコ,sidedish,dessert,299,229,0.1
K02,カプチーノ(アイスケーキ),sidedish,dessert,199,114,0.1
K03,コーヒーゼリー(ミルクアイスのせ),sidedish,dessert,299,162,0.1
K04,ミルクアイスのせシナモンフォッカチオ,sidedish,dessert,319,346,0.9
K05,ミルクジェラート,sidedish,dessert,199,100,0.1
K06,イタリアンプリン,sidedish,dessert,249,216,0.1
K07,チョコレートケーキ,sidedish,dessert,299,166,0.1
K08,プリンとカプチーノの盛合せ(季節限定),sidedish,dessert,399,330,0.2
K09,いちごソースのパンナコッタ,sidedish,dessert,299,184,0.2
K10,カシスとブルーベリーのパンナコッタ(季節限定),sidedish,dessert,399,186,0.1
K11,すっきりレモンのシャーベット,sidedish,dessert,199,127,0.0
K12,プリンとティラミス クラシコの盛合せ,sidedish,dessert,499,445,0.2
K13,トリフアイクリーム,sidedish,dessert,369,164,0.1
K14,とろけるティラミス&コーヒーゼリー,sidedish,dessert,399,284,0.1
L01,キリン一番搾り(ジョッキ),drink,alcohol,399,-,-
L02,キリン一番搾り(グラスビール),drink,alcohol,299,-,-
L03,サントリー オールフリー,drink,alcohol,259,-,-
L04,サントリー -196℃ ストロングゼロ ダブルレモン,drink,alcohol,379,-,-
M01,グラスワイン,drink,alcohol,100,-,-
M02,デカンタ(250ml),drink,alcohol,200,-,-
M03,デカンタ(500ml),drink,alcohol,399,-,-
M04,マグナム(1500ml),drink,alcohol,1100,-,-
M10,ランブルスコセッコ(赤・辛口),drink,alcohol,1100,-,-
M11,ランブルスコ(ロゼ・甘口),drink,alcohol,1100,-,-
M12,ベルデッキオ(辛口・中),drink,alcohol,1100,-,-
M13,キャンティ(辛口・やや重い),drink,alcohol,1100,-,-
M14,サイゼリヤプレミアム赤(辛口・重い),drink,alcohol,2200,-,-
M15,サイゼリヤプレミアム白(辛口・重い),drink,alcohol,2200,-,-
M16,キャンティ ルフィナ リゼルパ(辛口・重い),drink,alcohol,2200,-,-
R01,トッピング半熟卵,sidedish,topping,69,90,0.2
R02,ペコリーノ・ロマーノ,sidedish,topping,100,94,0.9
R03,ガーリックガルム付きディアボラ風ソース,sidedish,sauce,149,99,1.1
R04,ディアボラ風ソース,sidedish,sauce,100,72,0.3
R05,トッピングチーズ,sidedish,topping,100,-,-
Z03,セットドリンクバー,drink,drinkbar,190,-,-
,アスパラガスのアーリオ・オーリオ(季節限定),meal,pasta,499,756,2.5
EOL
)

if [ -n "${ALL+x}" ]; then
  if [ -n "${LONG+x}" ]; then
    echo "${MENU}" | sed -E 's/^[^,]*,//'
  else
    echo "${MENU}" | awk -F, '{print $2}'
  fi
else
  if [ -n "${LONG+x}" ]; then
    echo "${MENU}" | shuf -n1 | sed -E 's/^[^,]*,//'
  else
    echo "${MENU}" | shuf -n1 | awk -F, '{print $2}'
  fi
fi
