#!/usr/bin/env bash
set -eu

usage() {
  cat << EOL
Usage:
  $0 [Options]

Options:
  -a    display all menu
  -h    display this help and exit
  -l    use a long listing format
EOL
  exit
}

while getopts ahl OPT; do
  case $OPT in
    a)
      ALL=1
      ;;
    h)
      usage
      ;;
    l)
      LONG=1
      ;;
    \?)
      usage
      ;;
  esac
done

# Name,Category,Type,Price,Calorie,Salt
MENU=$(cat << EOL
彩りイタリアンサラダ,sidedish,salad,349,257,1.7
彩りイタリアンサラダ(Lサイズ),sidedish,salad,499,385,2.5
小エビのサラダ,sidedish,salad,349,126,1.4
小エビのサラダ(Lサイズ),sidedish,salad,499,189,2.1
チキンとブロッコリーのサラダ,sidedish,salad,349,182,1.7
チキンとブロッコリーのサラダ(Lサイズ),sidedish,salad,499,274,2.5
半熟卵のチキンとブロッコリーのサラダ,sidedish,salad,418,272,1.9
わかめとオクラのサラダ,sidedish,salad,349,143,3.0
わかめとオクラのサラダ(Lサイズ),sidedish,salad,499,214,4.4
トッピング半熟卵,sidedish,appetizer,69,90,0.2
とろとろ玉ねぎのスープ(季節限定),sidedish,soup,299,317,2.4
コーンクリームスープ,sidedish,soup,149,142,1.1
マッシュルームスープ(季節限定),sidedish,soup,149,130,0.9
辛味チキン,sidedish,appetizer,299,374,2.2
エスカルゴのオーブン焼き,sidedish,appetizer,399,256,1.6
ムール貝のガーリック焼き,sidedish,appetizer,399,164,1.3
チョリソー,sidedish,appetizer,399,393,2.0
野菜ソースのグリルソーセージ,sidedish,appetizer,399,570,3.1
ガーリックトースト,sidedish,appetizer,189,252,1.1
ミニフィセル,sidedish,appetizer,169,188,1.0
プチフォッカ,sidedish,appetizer,139,214,0.8
セットプチフォッカ,sidedish,appetizer,79,107,0.4
フォッカチオ,sidedish,appetizer,119,214,0.8
シナモンフォッカチオ,sidedish,appetizer,169,246,0.8
フリウリ風フリコ,sidedish,appetizer,299,333,1.0
チーズたっぷりフリウリ風フリコ,sidedish,appetizer,399,534,1.8
柔らか青豆の温サラダ,sidedish,appetizer,199,213,0.8
ペコリーノチーズの柔らか青豆の温サラダ,sidedish,appetizer,299,272,1.4
削りたてペコリーノチーズ,sidedish,appetizer,100,59,0.6
ほうれん草のソテー,sidedish,appetizer,199,123,1.1
半熟卵のほうれん草のソテー,sidedish,appetizer,268,213,1.3
キャベツとアンチョビのソテー,sidedish,appetizer,199,80,1.5
セロリのピクルス(季節限定),sidedish,appetizer,199,52,1.3
ポップコーンシュリンプ,sidedish,appetizer,299,215,1.4
熟成ミラノサラミ,sidedish,appetizer,299,95,1.1
熟成ミラノサラミ(Wサイズ),sidedish,appetizer,598,190,2.2
フレッシュチーズとトマトのサラダ,sidedish,appetizer,299,200,0.4
フレッシュチーズとトマトのサラダ(Wサイズ),sidedish,appetizer,598,400,0.8
プロシュート,sidedish,appetizer,399,162,1.8
プロシュート(Wサイズ),sidedish,appetizer,798,324,3.6
グラスワイン,drink,alcohol,100,0,0.0
デカンタ(250ml),drink,alcohol,200,0,0.0
デカンタ(500ml),drink,alcohol,399,0,0.0
マグナム(1500ml),drink,alcohol,1100,0,0.0
ランブルスコセッコ(赤)辛口,drink,alcohol,1100,0,0.0
ランブルスコ(ロゼ)甘口,drink,alcohol,1100,0,0.0
ベルデッキオ(辛口・中),drink,alcohol,1100,0,0.0
キャンティ(辛口・やや重い),drink,alcohol,1100,0,0.0
キャンティルフィナリゼルパ(辛口・重い),drink,alcohol,2200,0,0.0
サイゼリヤプレミアム(辛口・重い),drink,alcohol,2200,0,0.0
キリン一番搾り(ジョッキ),drink,alcohol,399,0,0.0
キリン一番搾り(グラスビール),drink,alcohol,299,0,0.0
サントリーオールフリー,drink,alcohol,259,0,0.0
ストロングゼロダブルレモン,drink,alcohol,379,0,0.0
セットドリンクバー,drink,drinkbar,190,0,0.0
バッファローモッツァレラのピザ,meal,pizza,499,575,2.3
マルゲリータピザ,meal,pizza,399,568,2.5
パンチェッタのピザ,meal,pizza,399,646,2.9
半熟卵のパンチェッタのピザ,meal,pizza,468,736,3.1
野菜ときのこのピザ,meal,pizza,399,593,2.9
アンチョビのピザ(ルーコラ葉入り),meal,pizza,399,543,4.7
たっぷりコーンのピザ,meal,pizza,399,669,2.8
たらこクリームのピザ,meal,pizza,399,615,3.3
アーリオ・オーリオ,meal,pasta,299,457,1.4
アーリオ・オーリオ(Wサイズ),meal,pasta,576,914,2.8
ペペロンチーノ,meal,pasta,299,457,1.4
ペペロンチーノ(Wサイズ),meal,pasta,576,914,2.8
ミートソースボロニア風,meal,pasta,399,552,2.5
ミートソースボロニア風(Wサイズ),meal,pasta,776,1104,5.0
半熟卵のミートソースボロニア風,meal,pasta,468,642,2.7
タラコソースシシリー風,meal,pasta,399,550,2.0
タラコソースシシリー風(Wサイズ),meal,pasta,776,1100,4.0
パルマ風スパゲッティ,meal,pasta,399,671,2.6
パルマ風スパゲッティ(Wサイズ),meal,pasta,776,1342,5.2
キャベツのペペロンチーノ,meal,pasta,399,587,1.6
キャベツのペペロンチーノ(Wサイズ),meal,pasta,776,1174,3.2
たっぷり小エビのオーロラソース,meal,pasta,599,663,3.0
牛すね肉のラグーソース,meal,pasta,599,638,3.1
イカの墨入りスパゲッティ,meal,pasta,499,579,2.2
イカの墨入りスパゲッティ(Wサイズ),meal,pasta,976,1158,4.4
カルボナーラ,meal,pasta,499,737,2.0
カルボナーラ(Wサイズ),meal,pasta,976,1474,4.0
ナポリジェノベーゼ,meal,pasta,499,516,2.2
ナポリジェノベーゼ(Wサイズ),meal,pasta,976,1032,4.4
アラビアータ,meal,pasta,399,601,2.5
アラビアータ(Wサイズ),meal,pasta,776,1202,5.0
ミラノ風ドリア,meal,doria,299,521,2.5
チーズたっぷりミラノ風ドリア,meal,doria,399,722,3.4
半熟卵のミラノ風ドリア,meal,doria,368,611,2.7
セットプチフォッカ付きミラノ風ドリア,meal,doria,378,628,2.9
いろどり野菜のミラノ風ドリア,meal,doria,399,570,3.0
エビとイカのドリア,meal,doria,499,624,2.9
ほうれん草のグラタン,meal,gratin,399,521,1.9
シーフードグラタン,meal,gratin,499,537,2.2
シーフードパエリア,meal,rice,599,595,3.6
エビと野菜のトマトクリームリゾット,meal,rice,399,311,2.3
ハヤシ&ターメリックライス,meal,rice,499,676,3.9
半熟卵のハヤシ&ターメリックライス,meal,rice,568,766,4.1
ミックスグリル,meal,hamburg,599,868,4.3
ハンバーグステーキ,meal,hamburg,399,560,2.8
ディアボラ風ハンバーグ,meal,hamburg,499,632,3.1
デミグラスソースのハンバーグ,meal,hamburg,499,606,3.1
イタリアンハンバーグ,meal,hamburg,499,670,2.9
焼肉とハンバーグの盛合せ,meal,hamburg,599,753,3.7
リブステーキ,meal,steak,999,606,2.0
トッピングディアボラ風ソース(ガーリックガルム付き),sidedish,sauce,149,99,1.1
若鶏のディアボラ風,meal,chicken,499,585,2.7
柔らかチキンのチーズ焼き,meal,chicken,499,628,2.6
パンチェッタと若鶏のグリル,meal,chicken,599,708,3.1
ライス,sidedish,rice,169,303,0.0
ラージライス,sidedish,rice,219,454,0.0
スモールライス,sidedish,rice,119,151,0.0
ティラミス クラシコ,sidedish,dessert,299,229,0.1
プリンとティラミス クラシコの盛合せ,sidedish,dessert,499,445,0.2
とろけるティラミス&コーヒーゼリー,sidedish,dessert,399,284,0.1
グラッパ,drink,alcohol,379,0,0.0
プリンとヘーゼルナッツの盛合せ(季節限定),sidedish,dessert,399,359,0.1
ヘーゼルナッツ(アイスケーキ)(季節限定),sidedish,dessert,199,143,0.0
いちごソースのパンナコッタ,sidedish,dessert,299,184,0.2
トリフアイスクリーム,sidedish,dessert,369,164,0.1
ミルクジェラート,sidedish,dessert,199,100,0.1
すっきりレモンのシャーベット,sidedish,dessert,199,127,0.0
イタリアンプリン,sidedish,dessert,249,216,0.1
チョコレートケーキ,sidedish,dessert,299,166,0.1
コーヒーゼリー(ミルクアイスのせ),sidedish,dessert,299,162,0.1
ミルクアイスのせシナモンフォッカチオ,sidedish,dessert,319,346,0.9
皮付き新じゃがのチーズグラタン(季節限定),meal,gratin,399,417,2.4
EOL
)

if [ -n "${ALL+x}" ]; then
  if [ -n "${LONG+x}" ]; then
    echo "${MENU}"
  else
    echo "${MENU}" | awk -F, '{print $1}'
  fi
else
  if [ -n "${LONG+x}" ]; then
    echo "${MENU}" | shuf -n1
  else
    echo "${MENU}" | shuf -n1 | awk -F, '{print $1}'
  fi
fi
